# Color definitions
color-jwpimareas-header=#1378b1
color-jwpimareas-header-text=#fff
color-jwpimareas-body=#f0eee9
color-jwpimareas-body-text=#263238
color-jwpimareas-dark-bg=#4db6e6
color-jwpimareas-dark-text=#000
color-jwpimareas-error-bg=#fff
color-jwpimareas-error-text=#a12133
color-jwpimareas-footer-bg=#faca40
color-jwpimareas-footer-text=#000
