services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JanWieland\PimAreaBricks\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/PimAreaBricksBundle.php"
  JanWieland\PimAreaBricks\Installer:
    public: true
