pimcore:
  assets:
    image:
      thumbnails:
        definitions:
          JWpimAreas-content-16-9:
            group: JWpimAreas
            format: AUTO
            items:
              - method: cover
                arguments:
                  width: 480
                  height: 270
                  positioning: center
                  forceResize: true
            medias:
              "min-width: 480px":
                - method: cover
                  arguments:
                    width: 936
                    height: 526
                    positioning: center
                    forceResize: true
              "min-width: 1040px":
                - method: cover
                  arguments:
                    width: 1280
                    height: 720
                    positioning: center
                    forceResize: true
