pimcore:
  assets:
    image:
      thumbnails:
        definitions:
          content-16-9:
            group: JWpimAreas
            format: AUTO
            preserve_color: false
            preserve_metadata: false
            items:
              - method: cover
                arguments:
                  width: 480
                  height: 270
                  positioning: center
                  forceResize: true
            medias:
              "min-width: 480px":
                items:
                  - method: cover
                    arguments:
                      width: 936
                      height: 526
                      positioning: center
                      forceResize: true
              "min-width: 1040px":
                items:
                  - method: cover
                    arguments:
                      width: 1280
                      height: 720
                      positioning: center
                      forceResize: true
